services:
  db:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d myapp_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      # mkcert　SSL通信にて一時的に使用↓
      #- ./config/certs:/config/certs:ro
    environment:
      TZ: Asia/Tokyo
      ## ↓Rspecで追加
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      #　mkcertSSL通信にて一時的に使用　300013001から戻し
      - "3000:3000"
    user: "1000:1000"
    depends_on:
      db:
        condition: service_healthy
  chrome:
    image: selenium/standalone-chrome
    shm_size: 2g
    ports:
      - 4444:4444
volumes:
  postgresql_data: